version: '3.8'

services:
  dns_master:
    build:
      context: .
      dockerfile: ./DNS/MASTER/dockerfile
    container_name: dns_master
    hostname: dns_master.samez.fr
    networks:
      my_network:
        ipv4_address: 192.168.1.2
    ports:
      - "1053:53/udp"
      - "1054:53/tcp"
    volumes:
      - ./DNS/MASTER/named.conf.local:/etc/bind/named.conf.local
      - ./DNS/MASTER/named.conf.options:/etc/bind/named.conf.options
      - ./DNS/MASTER/forward.info.local:/etc/bind/forward.info.local
      - ./DNS/MASTER/reverse.info.local:/etc/bind/reverse.info.local

  dns_slave:
    build:
      context: .
      dockerfile: ./DNS/SLAVE/dockerfile
    container_name: dns_slave
    hostname: dns_slave..samez.fr
    networks:
      my_network:
        ipv4_address: 192.168.1.3
    ports:
      - "1051:53/udp"
      - "1052:53/tcp"
    volumes:
      - ./DNS/SLAVE/named.conf.local:/etc/bind/named.conf.local

  ftp:
    build:
      context: .
      dockerfile: ./FTP/dockerfile
    container_name: ftp_server
    hostname: ftp.samez.fr
    networks:
      my_network:
        ipv4_address: 192.168.1.4
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    volumes:
      - ./ftp:/ftp
    restart: unless-stopped

  mail:
    build:
      context: .
      dockerfile: ./MAIL/dockerfile
    container_name: mail_server
    hostname: mail.samez.fr
    networks:
      my_network:
        ipv4_address: 192.168.1.5
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./mail:/var/mail

  voip:
    build:
      context: .
      dockerfile: ./VOIP/dockerfile
    container_name: voip_server
    hostname: voip.samez.fr
    networks:
      my_network:
        ipv4_address: 192.168.1.6
    ports:
      - "5060:5060/udp"
      - "5061:5061/udp"
    volumes:
      - ./asterisk:/etc/asterisk

  vpn:
    build:
      context: .
      dockerfile: ./VPN/dockerfile
    container_name: vpn_server
    hostname: vpn.samez.fr
    networks:
      my_network:
        ipv4_address: 192.168.1.7
    ports:
      - "1194:1194/udp"
    cap_add:
      - Net_ADMIN
    volumes:
      - ./VPN:/etc/openvpn

  dhcp:
    build:
      context: .
      dockerfile: ./DHCP/dockerfile
    container_name: dhcp_server
    hostname: dhcp.samez.fr
    networks:
      my_network:
        ipv4_address: 192.168.1.8
    ports:
      - "67:67/udp"
    volumes:
      - ./DHCP/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - dhcp-leases:/var/lib/dhcp

  web:
    build:
      context: .
      dockerfile: ./WEB/dockerfile
    container_name: web_sercer
    hostname: web.samez.fr
    networks:
      my_network:
        ipv4_address: 192.168.1.9
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html

  pc:
    build: 
      context : .
      dockerfile: ./PC/dockerfile
    container_name: pc
    hostname: pc
    networks:
      my_network:
    tty: true
    command: /bin/bash

  router:
    build:
      context: .
      dockerfile: ./ROUTER/dockerfile
    container_name: router
    hostname: router
    networks:
      - router_network
    volumes:
      - ./ROUTER/router-config:/etc/router-config
    privileged: true 
    cap_add:
      - NET_ADMIN  
    restart: always 
  
  #vr:
  #  build:
  #    context: .
  #    dockerfile: ./VR/dockerfile
  #  container_name: vr
  #  hostname: vr
  #  networks:
  #    - router_network

networks:
  my_network:
    driver: bridge # Bridge
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
  
  router_network:
    driver: bridge

volumes:
  dhcp-leases: