version: '3.8'

services:
  dns_master:
    build:
      context: .
      dockerfile: ./DNS/MASTER/dockerfile
    networks:
      my_network:
        ipv4_address: 192.168.1.2
    ports:
      - "1053:53/udp"
      - "1054:53/tcp"
    volumes:
      - ./DNS/MASTER/named.conf.local:/etc/bind/named.conf.local
      - ./DNS/MASTER/named.conf.options:/etc/bind/named.conf.options
      - ./DNS/MASTER/forward.info.local:/etc/bind/forward.info.local
      - ./DNS/MASTER/reverse.info.local:/etc/bind/reverse.info.local

  dns_slave:
    build:
      context: .
      dockerfile: ./DNS/SLAVE/dockerfile
    networks:
      my_network:
        ipv4_address: 192.168.1.3
    ports:
      - "1051:53/udp"
      - "1052:53/tcp"
    volumes:
      - ./DNS/SLAVE/named.conf.local:/etc/bind/named.conf.local

  ftp:
    build:
      context: .
      dockerfile: ./FTP/dockerfile
    networks:
      my_network:
        ipv4_address: 192.168.1.4
    ports:
      - "21:21"
    volumes:
      - ./ftp:/ftp

  mail:
    build:
      context: .
      dockerfile: ./MAIL/dockerfile
    networks:
      my_network:
        ipv4_address: 192.168.1.5
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./mail:/var/mail

  voip:
    build:
      context: .
      dockerfile: ./VOIP/dockerfile
    networks:
      my_network:
        ipv4_address: 192.168.1.6
    ports:
      - "5060:5060/udp"
      - "5061:5061/udp"
    volumes:
      - ./asterisk:/etc/asterisk

  vpn:
    build:
      context: .
      dockerfile: ./VPN/dockerfile
    networks:
      my_network:
        ipv4_address: 192.168.1.7
    ports:
      - "1194:1194/udp"
    volumes:
      - ./VPN:/etc/openvpn
    cap_add:
      - Net_ADMIN

  web:
    build:
      context: .
      dockerfile: ./WEB/dockerfile
    networks:
      my_network:
        ipv4_address: 192.168.1.8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
