FROM ubuntu:20.04

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Set the time zone
ENV TZ=Europe/Paris

# Update package list and install essential packages, including locales
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    asterisk \
    tzdata \
    locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN echo "voip.samez.fr" > /etc/hostname


# Expose necessary ports
EXPOSE 5060 5061

# Default command to run Asterisk in the foreground
CMD ["asterisk", "-f"]
